import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Link from "next/link";
import { ChevronDown } from "tabler-icons-react";

export default function Home() {
  return (
    <div className={styles.main_container}>
      <Head>
        <title>Ahmed J. Jibril | Frontend-developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <main className={styles.main_section}>
        <section className={styles.home_container}>
          <div className={styles.home_overlay}></div>
          <div className={styles.home_content}>
            <div className={styles.top_section}>
              <div className={styles.left_content}>
                <div className={styles.greeting}>
                  <div className={styles.line}></div>
                  <span>HELLO THERE</span>
                </div>
                <h1>I am Ahmed J. Jibril</h1>
                <span>I am a Frontend Developer</span>
              </div>
              <div className={styles.right_content}>
                <Link href={"/about_container"}>
                  <button>MORE ABOUT ME</button>
                </Link>
                <Link href={"/work_container"}>
                  <button>LATEST PROJECTS</button>
                </Link>
              </div>
            </div>
            <div className={styles.bottom_section}>
              <span>
                SCROLL DOWN <ChevronDown />
              </span>
            </div>
          </div>
        </section>
        <section className={styles.about_container}>About</section>
        <section className={styles.work_container}>Work</section>
        <section className={styles.contact_container}>
          <div className={styles.contact_overlay}></div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
